---
name: eats

releases:
- name: etcd
  version: latest
- name: consul
  version: latest
- name: bosh-warden-cpi
  version: 34
  url: https://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=34
  sha1: 5b102afe81bea5927983575aeafddbd93f6a21a5
- name: turbulence
  version: 0.6
  url: https://bosh.io/d/github.com/cppforlife/turbulence-release?v=0.6
  sha1: 5222108e2aa500bb60205d7a0e6f654dde391f36

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: acceptance-tests
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: private}]
  jobs:
  - name: acceptance-tests
    release: etcd

properties:
  etcd:
    acceptance_tests:
      bosh:
        target: ((bosh_target))
        username: ((bosh_username))
        password: ((bosh_password))
        director_ca_cert: ((bosh_director_ca_cert))
      parallel_nodes: 1
      etcd_release_version: latest
      enable_turbulence_tests: ((enable_turbulence_tests))

update:
  serial: true
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-180000
  update_watch_time: 1000-180000
